- .github/ISSUE_TEMPLATE/issue_template.md
- close #11
<br/>
- 우선 이슈 템플릿 적용되게 코드 수정함
- 이제부터 CD시작!
> [FIX] 이슈 템플릿 수정

- src/main/java/com/soptie/server/doll/controller/DollController.java
- src/main/java/com/soptie/server/doll/dto/DollImageResponse.java
- src/main/java/com/soptie/server/doll/entity/Doll.java
- src/main/java/com/soptie/server/doll/entity/DollImage.java
- src/main/java/com/soptie/server/doll/message/ErrorMessage.java
- src/main/java/com/soptie/server/doll/message/ResponseMessage.java
- src/main/java/com/soptie/server/doll/repository/DollRepository.java
- src/main/java/com/soptie/server/doll/service/DollService.java
- src/main/java/com/soptie/server/doll/service/DollServiceImpl.java
- src/main/resources/static/docs/open-api-3.0.1.json
- src/test/java/com/soptie/server/doll/controller/DollControllerTest.java
- src/test/java/com/soptie/server/doll/fixture/DollFixture.java
> [FEAT] 인형 이미지 조회

- src/main/java/com/soptie/server/routine/entity/happiness/HappinessRoutine.java
- src/main/java/com/soptie/server/routine/entity/happiness/HappinessTheme.java
- close #30 
<br/>
- 행복루틴 엔티티 수정 (테마 기준으로 이미지 통일 반영)
- DB 반영은 완료
> [FIX] 행복 루틴 엔티티 수정

- src/main/resources/static/docs/open-api-3.0.1.json
- src/test/java/com/soptie/server/doll/controller/DollControllerTest.java
- close #43 
<br/>
- build 통과했습니다.
> [HOTFIX] 에러 대응

- scripts/deploy.sh
> [FIX] 배포 jar 이름 수정

- src/main/resources/static/docs/open-api-3.0.1.json
- src/test/java/com/soptie/server/base/BaseControllerTest.java
> [HOTFIX] 빌드 에러 대응

- src/main/java/com/soptie/server/common/config/SecurityConfig.java
- src/test/java/com/soptie/server/ServerApplicationTests.java
> [CHORE] 권한 경로 추가, 테스트 일부 삭제

- src/main/resources/static/docs/open-api-3.0.1.json
- src/test/java/com/soptie/server/auth/controller/AuthControllerTest.java
- close #49 
<br/>
명예 김소현 고마워!
> [TEST] 소셜 로그인 api 테스트

- src/main/java/com/soptie/server/common/config/SecurityConfig.java
- close #53 
<br/>
- 데일리 루틴 테마 리스트 조회
- 테마 리스트 별 데일리 루틴 리스트 조회
- 캐릭터 이미지 정보 조회
위 경로를 권한 허용해주었습니다.
> [ADD] 권한 허용 경로 추가

- src/main/java/com/soptie/server/memberRoutine/controller/MemberDailyRoutineController.java
- src/main/resources/static/docs/open-api-3.0.1.json
- src/test/java/com/soptie/server/memberRoutine/controller/MemberDailyRoutineControllerTest.java
- src/test/java/com/soptie/server/routine/controller/DailyRoutineControllerTest.java
- close #60 
<br/>
- 식별자 분리하여 해결했습니다.
> [FIX] 테스트코드 누락 해결: 식별자 분리

- src/main/java/com/soptie/server/doll/service/DollService.java
- src/main/java/com/soptie/server/doll/service/DollServiceImpl.java
- src/main/java/com/soptie/server/member/controller/MemberController.java
- src/main/java/com/soptie/server/member/dto/MemberProfileRequest.java
- src/main/java/com/soptie/server/member/entity/Member.java
- src/main/java/com/soptie/server/member/message/ErrorMessage.java
- src/main/java/com/soptie/server/member/message/ResponseMessage.java
- src/main/java/com/soptie/server/member/service/MemberService.java
- src/main/java/com/soptie/server/member/service/MemberServiceImpl.java
- src/main/java/com/soptie/server/memberDoll/entity/MemberDoll.java
- src/main/java/com/soptie/server/memberDoll/repository/MemberDollRepository.java
- src/main/java/com/soptie/server/memberDoll/service/MemberDollService.java
- src/main/java/com/soptie/server/memberDoll/service/MemberDollServiceImpl.java
- src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineService.java
- src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java
- src/main/resources/static/docs/open-api-3.0.1.json
- close #62 
<br/>
- 프로필 생성 성공
- 데이터베이스 변화
- 프로필 중복 생성 방지 -> 인형은 다시 선택 불가!!
setMember에 대한 부분에 대해 좀 더 고민을 해봐야할 거 같긴 합니다.
> [FEAT] 프로필 생성 API

- src/main/java/com/soptie/server/member/entity/Cotton.java
- src/main/java/com/soptie/server/member/entity/Member.java
- src/main/java/com/soptie/server/memberRoutine/entity/daily/MemberDailyRoutine.java
- src/main/resources/static/docs/open-api-3.0.1.json
- close #60 
<br/>
데일리 루틴을 달성할 때 솜 개수를 추가하는 것을 깜빡하여 바로 추가 진행했습니다 :)
> [ADD] 데일리 솜 개수 추가 로직 추가

- README.md
> 서버 2차 과제에 맞는 아키텍처 수정, 모델 수정

- src/main/java/com/soptie/server/member/controller/MemberController.java
- src/main/java/com/soptie/server/member/dto/CottonCountResponse.java
- src/main/java/com/soptie/server/member/entity/Cotton.java
- src/main/java/com/soptie/server/member/entity/CottonType.java
- src/main/java/com/soptie/server/member/entity/Member.java
- src/main/java/com/soptie/server/member/message/ErrorMessage.java
- src/main/java/com/soptie/server/member/message/ResponseMessage.java
- src/main/java/com/soptie/server/member/service/MemberService.java
- src/main/java/com/soptie/server/member/service/MemberServiceImpl.java
- src/main/java/com/soptie/server/memberDoll/entity/MemberDoll.java
- src/main/resources/static/docs/open-api-3.0.1.json
- src/test/java/com/soptie/server/member/controller/MemberControllerTest.java
- close #84 
<br/>
- 솜뭉치 주기 성공 시
- 솜뭉치 주기 실패 시
없다.
> [FEAT] 솜뭉치 주기 api

- src/main/resources/static/docs/open-api-3.0.1.json
- src/test/java/com/soptie/server/routine/controller/HappinessRoutineControllerTest.java
> [HOTFIX] 테스트 실패 대응

- src/main/java/com/soptie/server/memberRoutine/repository/MemberHappinessRoutineRepository.java
- src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImpl.java
- src/main/resources/static/docs/open-api-3.0.1.json
> [ADD] 행복 루틴 추가 시 이미 행복 루틴을 가진 회원이면 예외 처리 추가

- src/main/java/com/soptie/server/member/service/MemberServiceImpl.java
- close #114 
<br/>
급해서 바로 머지하겠습니다 ㅠㅠ
> [FIX] 프로필 생성 오류 수정

- src/main/resources/static/docs/open-api-3.0.1.json
- src/test/java/com/soptie/server/memberRoutine/controller/MemberHappinessRoutineControllerTest.java
- src/test/java/com/soptie/server/memberRoutine/fixture/MemberHappinessRoutineFixture.java
> [TEST] testcode 작성하기

- src/main/java/com/soptie/server/memberRoutine/dto/MemberHappinessRoutineRequest.java
- src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImpl.java
- src/test/java/com/soptie/server/memberRoutine/controller/MemberHappinessRoutineControllerTest.java
> [CHORE] 변수명 수정

- src/main/java/com/soptie/server/routine/dto/HappinessSubRoutinesResponse.java
- close #134 
<br/>
none
- content 데이터를 받는 쪽에 timeTaken이 들어가있어 수정합니다.
> [FIX] 응답 데이터 수정

- src/main/java/com/soptie/server/member/message/ErrorCode.java
- src/main/java/com/soptie/server/member/service/MemberServiceImpl.java
- close #137 
<br/>
위 이미지와 같은 에러가 지속적으로 발생해서 예외 처리를 추가했어요.
> [ADD] 회원의 인형 존재 여부에 따라 예외 처리 추가

- src/main/java/com/soptie/server/member/service/MemberServiceImpl.java
- close #이슈번호
<br/>
none
- nonNull -> isNull 수정
- 메소드 위치 변경 (private는 사용 위치와 가까운 곳에 배치)
> [FIX] 메소드 수정

- src/main/java/com/soptie/server/auth/dto/SignInResponse.java
- src/main/java/com/soptie/server/auth/service/AuthServiceImpl.java
- src/main/java/com/soptie/server/member/service/MemberService.java
- src/main/java/com/soptie/server/member/service/MemberServiceImpl.java
- src/main/resources/static/docs/open-api-3.0.1.json
- src/test/java/com/soptie/server/auth/controller/AuthControllerTest.java
- close #131 
<br/>
SignInResponse에 boolean isRegistered 추가했습니다.
> [ADD] 프로필 존재 여부 response에 추가

- src/main/java/com/soptie/server/auth/service/AuthServiceImpl.java
- src/main/java/com/soptie/server/common/util/Constant.java
- src/main/java/com/soptie/server/doll/service/DollServiceImpl.java
- src/main/java/com/soptie/server/member/entity/Cotton.java
- src/main/java/com/soptie/server/member/entity/Member.java
- src/main/java/com/soptie/server/member/service/MemberService.java
- src/main/java/com/soptie/server/member/service/MemberServiceImpl.java
- src/main/java/com/soptie/server/memberDoll/service/MemberDollServiceImpl.java
- src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineService.java
- src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java
- src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineService.java
- src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImpl.java
- src/main/java/com/soptie/server/routine/service/DailyRoutineServiceImpl.java
- src/main/java/com/soptie/server/routine/service/HappinessRoutineServiceImpl.java
- close #142 
<br/>
캡슐화를 중심으로 자잘한 코드 리팩토링을 진행했습니다.
none
> [REFACTOR] 코드 리팩토링

- src/main/java/com/soptie/server/member/entity/Member.java
- src/main/java/com/soptie/server/memberRoutine/controller/MemberDailyRoutineController.java
- src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineService.java
- src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java
- src/main/java/com/soptie/server/routine/controller/DailyRoutineController.java
- src/main/java/com/soptie/server/routine/service/DailyRoutineService.java
- src/main/java/com/soptie/server/routine/service/DailyRoutineServiceImpl.java
- src/main/resources/static/docs/open-api-3.0.1.json
- src/test/java/com/soptie/server/memberRoutine/controller/MemberDailyRoutineControllerTest.java
- src/test/java/com/soptie/server/routine/controller/DailyRoutineControllerTest.java
- close #이슈번호
<br/>
- 로직 변경으로 인해 수정합니다.
> [FIX] 데일리 루틴 삭제 수정

- src/main/resources/static/docs/open-api-3.0.1.json
- src/test/java/com/soptie/server/memberRoutine/controller/MemberDailyRoutineControllerTest.java
> [FIX] 테스트 실패 이슈 대응

- src/main/java/com/soptie/server/member/entity/Member.java
- src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineService.java
- src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java
- src/main/java/com/soptie/server/routine/service/DailyRoutineServiceImpl.java
- src/test/java/com/soptie/server/routine/service/DailyRoutineServiceTest.java
- close #157 
<br/>
- Entity 내에 메서드를 포함시켜 캡슐화 작업 진행했습니다.
> [REFACTOR] 캡슐화

- src/main/java/com/soptie/server/auth/service/AuthServiceImpl.java
- src/main/java/com/soptie/server/memberDoll/entity/MemberDoll.java
- close #162 
- 숫자 안돼~
소통을 잘하자.
> [FIX] 인형 이름 숫자 금지

- src/main/java/com/soptie/server/doll/message/ErrorCode.java
- src/main/java/com/soptie/server/member/entity/Cotton.java
- src/main/java/com/soptie/server/member/entity/Member.java
- close #167
<br/>
- 행복 솜뭉치를 주면 인형의 행복 솜뭉치 개수가 추가됩니다.
> [FIX] 인형이 먹은 행복 솜뭉치 데이터 저장

- src/main/java/com/soptie/server/auth/controller/AuthController.java
- src/main/java/com/soptie/server/auth/dto/TokenResponse.java
- src/main/java/com/soptie/server/auth/jwt/JwtAuthenticationFilter.java
- src/main/java/com/soptie/server/auth/jwt/JwtValidationType.java
- src/main/java/com/soptie/server/auth/service/AppleServiceImpl.java
- src/main/java/com/soptie/server/auth/service/AuthService.java
- src/main/java/com/soptie/server/common/util/Constant.java
- src/main/java/com/soptie/server/doll/entity/DollImage.java
- src/main/java/com/soptie/server/doll/message/SuccessMessage.java
- src/main/java/com/soptie/server/doll/service/DollService.java
- src/main/java/com/soptie/server/member/entity/Cotton.java
- src/main/java/com/soptie/server/member/service/MemberService.java
- src/main/java/com/soptie/server/member/service/MemberServiceImpl.java
- src/main/java/com/soptie/server/memberDoll/entity/MemberDoll.java
- src/main/java/com/soptie/server/memberDoll/repository/MemberDollRepository.java
- src/main/java/com/soptie/server/memberRoutine/repository/MemberDailyRoutineRepository.java
- src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineService.java
- src/main/java/com/soptie/server/routine/message/SuccessMessage.java
- src/main/java/com/soptie/server/routine/repository/happiness/routine/HappinessRoutineCustomRepository.java
- src/main/java/com/soptie/server/routine/repository/happiness/routine/HappinessRoutineRepository.java
- src/main/java/com/soptie/server/routine/service/HappinessRoutineService.java
> [CHORE] constant 폴더로 상수 이동 및 코드 컨벤션에 맞게 수정

- src/main/java/com/soptie/server/common/config/SecurityConfig.java
- src/main/java/com/soptie/server/common/config/ValueConfig.java
- src/main/java/com/soptie/server/version/controller/VersionController.java
- src/main/java/com/soptie/server/version/dto/AppVersionResponse.java
- src/main/java/com/soptie/server/version/message/SuccessMessage.java
- src/main/java/com/soptie/server/version/service/VersionService.java
- src/main/java/com/soptie/server/version/service/VersionServiceImpl.java
- src/main/resources/static/docs/open-api-3.0.1.json
- src/test/java/com/soptie/server/version/controller/VersionControllerTest.java
- close #172 
<br/>
- 클라이언트 앱 버전 정보 조회입니다.
- static으로 데이터 값을 사용하면 메모리 낭비가 일어나지 않을까하여 getter로 가져오도록 했습니다.
- ValueConfig와 Constant의 역할이 동일하다고 생각하여 ValueConfig로 고정 값을 가져오도록 했습니다.
- 관련 제안하고 싶은 이슈입니다. -> [바로가기](https://github.com/Team-Sopetit/Sopetit-server/issues/173)
> [FEAT] 앱 버전 정보 조회

- src/main/java/com/soptie/server/member/controller/MemberController.java
- src/main/resources/static/docs/open-api-3.0.1.json
- src/test/java/com/soptie/server/member/controller/MemberControllerTest.java
> [CHORE] 솜뭉치 주기 api 경로 수정

- .github/workflows/deploy-prod.yml
- scripts/deploy.sh
- src/main/java/com/soptie/server/common/config/SecurityConfig.java
- src/main/resources/application-prod.yml
- close #182 
<br/>
- prod 서버 분리했습니다. (deploy 관련, 에러 로그 수집 분리, swagger 분리)
> [CHORE] prod 서버 분리

- src/main/resources/application-dev.yml
> [CHORE] 토큰 만료 시간 임시 변경

- src/main/java/com/soptie/server/common/config/ValueConfig.java
- src/main/resources/application-dev.yml
> [HOTFIX] 정규표현식 및 토큰 시간 수정

- src/main/java/com/soptie/server/common/config/ValueConfig.java
> [FIX] 정규표현식 수정

- src/main/java/com/soptie/server/routine/entity/happiness/HappinessTheme.java
- src/test/java/com/soptie/server/routine/service/HappinessRoutineServiceImplTest.java
- src/test/java/com/soptie/server/support/HappinessThemeFixture.java
> [TEST] 행복 루틴 테마 목록 조회 테스트 작성

- src/main/java/com/soptie/server/doll/entity/Doll.java
- src/main/java/com/soptie/server/doll/entity/DollImage.java
- src/test/java/com/soptie/server/doll/service/DollServiceImplTest.java
- src/test/java/com/soptie/server/support/DollFixture.java
- close #203 
<br/>
- getDollImage() 테스트 입니다.
> [TEST] DollService 테스트

- src/test/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImplTest.java
- src/test/java/com/soptie/server/support/MemberFixture.java
- #146
<br/>
회원 데일리 루틴 달성 테스트 완
> [TEST] 데일리루틴 달성 테스트

- src/main/java/com/soptie/server/memberRoutine/entity/happiness/MemberHappinessRoutine.java
- src/main/java/com/soptie/server/routine/entity/happiness/HappinessRoutine.java
- src/main/java/com/soptie/server/routine/entity/happiness/HappinessSubRoutine.java
- src/main/java/com/soptie/server/routine/entity/happiness/HappinessTheme.java
- src/main/java/com/soptie/server/routine/entity/happiness/RoutineImage.java
- src/test/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImplTest.java
- src/test/java/com/soptie/server/routine/fixture/HappinessRoutineFixture.java
- src/test/java/com/soptie/server/support/HappinessRoutineFixture.java
- src/test/java/com/soptie/server/support/HappinessSubRoutineFixture.java
- src/test/java/com/soptie/server/support/HappinessThemeFixture.java
- src/test/java/com/soptie/server/support/MemberHappinessRoutineFixture.java
- close #이슈번호
<br/>
회원이_행복루틴을_추가하면_회원의_행복루틴이_생성된다
> [TEST] 행복루틴 추가 테스트

- src/main/java/com/soptie/server/routine/entity/happiness/RoutineImage.java
- src/test/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImplTest.java
- src/test/java/com/soptie/server/routine/service/HappinessRoutineServiceImplTest.java
> [TEST] 행복 루틴 목록 조회 테스트

- src/main/java/com/soptie/server/auth/service/AuthServiceImpl.java
- src/main/resources/static/docs/open-api-3.0.1.json
- close #215 
<br/>
- reissueToken api 테스트
- 졸전 개발 중 소프티에서 리팩토링하고 싶은 부분이 생겨 pr 올립니다.
- 단순한 메소드 분리작업 진행했습니다.
> [REFACTOR] 토큰 재발급 api 리팩토링

- src/main/java/com/soptie/server/memberRoutine/controller/daily/MemberDailyRoutineApi.java
- #117 
<br/>
- 회원의 데일리 루틴 관련 API에 스웨거 정보(어노테이션)를 추가했습니다.
> [ADD] 회원의 데일리 루틴 Swagger 정보 추가

- src/main/java/com/soptie/server/routine/controller/happiness/HappinessRoutineApi.java
> [ADD] 행복 루틴 Swagger 정보 추가

- src/main/java/com/soptie/server/version/controller/VersionApi.java
- #117 
<br/>
- 버전 관련 API의 스웨거 정보(어노테이션)를 추가합니다.
> [ADD] 버전 Swagger 정보 추가

- src/main/java/com/soptie/server/auth/controller/AuthApi.java
- src/main/java/com/soptie/server/doll/controller/DollApi.java
- src/main/java/com/soptie/server/doll/message/ErrorCode.java
- src/main/java/com/soptie/server/member/controller/MemberApi.java
- src/main/java/com/soptie/server/member/entity/Member.java
- close #117 
<br/>
- AuthApi, DollApi
- MemberApi
> [ADD] Swagger 정보 추가

- src/main/java/com/soptie/server/memberRoutine/repository/MemberRoutineRepositoryImpl.java
- src/main/java/com/soptie/server/memberRoutine/repository/dto/MemberChallengeResponse.java
- src/main/java/com/soptie/server/routine/repository/RoutineRepositoryImpl.java
- close #이슈번호
<br/>
행복 루틴 전체 조회
회원 행복 루틴 삭제
> [HOTFIX] 행복 루틴 이슈 대응

- src/main/java/com/soptie/server/routine/adapter/RoutineFinder.java
- src/main/java/com/soptie/server/routine/repository/RoutineCustomRepository.java
- src/main/java/com/soptie/server/routine/repository/RoutineRepositoryImpl.java
- src/main/java/com/soptie/server/routine/service/RoutineService.java
- src/main/java/com/soptie/server/routine/service/dto/request/HappinessRoutineListGetServiceRequest.java
- close #이슈번호
<br/>
- 행복 루틴 전체 조회 이슈 대응
> [HOTFIX] 행복 루틴 조회

- src/main/java/com/soptie/server/routine/repository/RoutineRepositoryImpl.java
> [HOTFIX] 전체 조회 이슈 대응

- src/main/java/com/soptie/server/routine/service/dto/response/DailyRoutineListGetServiceResponse.java
- src/main/java/com/soptie/server/theme/entity/ThemeImageInfo.java
- src/test/java/com/soptie/server/support/fixture/ThemeFixture.java
- none
<br/>
- 데일리 루틴 조회 테마 배경 이미지 이슈 대응
hotfix
> [HOTFIX] 데일리 루틴 조회 배경 이미지 이슈 대응

- src/main/java/com/soptie/server/theme/controller/v1/dto/response/DailyThemeListGetResponse.java
- src/main/java/com/soptie/server/theme/entity/ThemeImageInfo.java
- src/main/java/com/soptie/server/theme/service/dto/response/ThemeListGetServiceResponse.java
- src/test/java/com/soptie/server/support/fixture/ThemeFixture.java
- none
<br/>
- 이슈 대응
- 실시간으로 리뷰 후 hotfix로 재배포 합니다.
> [HOTFIX] 데일리 루틴 아이콘 이미지 이슈 대응

- src/main/java/com/soptie/server/memberRoutine/controller/v1/dto/response/MemberHappinessRoutineGetResponse.java
- src/main/java/com/soptie/server/memberRoutine/service/dto/response/MemberHappinessRoutineGetServiceResponse.java
- none
<br/>
- none
- 카드 이미지 이슈 대응
> [HOTFIX] 구버전 이미지 이슈 대응

- src/main/java/com/soptie/server/common/config/ValueConfig.java
- close #262 
<br/>
- 안드로이드 앱 버전 업데이트
- 리뷰 및 승인 후 머지까지 가능하면 부탁드려요~
> [FIX] 안드로이드 앱 버전 업데이트

- src/main/java/com/soptie/server/memberRoutine/controller/v1/dto/response/MemberHappinessRoutineGetResponse.java
- src/main/java/com/soptie/server/memberRoutine/service/dto/response/MemberHappinessRoutineGetServiceResponse.java
- none
<br/>
- none
- 안드로이드 버전을 업데이트 완료했습니다.
> [FIX] 안드로이드 버전 업데이트

- src/main/java/com/soptie/server/common/config/SwaggerConfig.java
- close #239 
<br/>
- 스웨거 토큰이 적용되지 않는 이슈를 해결했습니다.
- none
> [FIX] 스웨거 토큰 이슈 대응

- src/main/java/com/soptie/server/auth/controller/AuthApi.java
- src/main/java/com/soptie/server/auth/jwt/CustomJwtAuthenticationEntryPoint.java
- src/main/java/com/soptie/server/auth/jwt/JwtAuthenticationFilter.java
- src/main/java/com/soptie/server/auth/jwt/UserAuthentication.java
- src/main/java/com/soptie/server/common/config/SecurityConfig.java
- src/main/java/com/soptie/server/doll/entity/Doll.java
- src/main/java/com/soptie/server/member/controller/dto/response/MemberHomeInfoGetResponse.java
- src/main/java/com/soptie/server/member/entity/Member.java
- src/main/java/com/soptie/server/memberRoutine/controller/v1/MemberDailyRoutineController.java
- src/main/java/com/soptie/server/memberRoutine/controller/v1/MemberHappinessRoutineController.java
- src/main/java/com/soptie/server/memberRoutine/entity/MemberRoutine.java
- src/main/java/com/soptie/server/memberRoutine/service/MemberRoutineUpdateService.java
- src/main/java/com/soptie/server/routine/entity/Challenge.java
- src/main/java/com/soptie/server/routine/service/dto/request/DailyRoutineListByThemeGetServiceRequest.java
- src/main/java/com/soptie/server/routine/service/dto/request/DailyRoutineListByThemesGetServiceRequest.java
- src/main/java/com/soptie/server/routine/service/dto/request/HappinessRoutineListGetServiceRequest.java
- src/main/java/com/soptie/server/routine/service/dto/request/HappinessSubRoutineListGetServiceRequest.java
- src/main/java/com/soptie/server/routine/service/dto/response/DailyRoutineListGetServiceResponse.java
- src/main/java/com/soptie/server/routine/service/dto/response/HappinessRoutineListGetServiceResponse.java
- src/main/java/com/soptie/server/routine/service/dto/response/HappinessSubRoutineListGetServiceResponse.java
- src/main/java/com/soptie/server/theme/controller/v1/dto/response/DailyThemeListGetResponse.java
- src/main/java/com/soptie/server/theme/controller/v1/dto/response/HappinessThemeListGetResponse.java
- src/main/java/com/soptie/server/theme/entity/Theme.java
- src/main/java/com/soptie/server/theme/service/dto/response/ThemeListGetServiceResponse.java
- src/main/java/com/soptie/server/version/controller/dto/response/AppVersionGetResponse.java
- src/main/java/com/soptie/server/version/service/dto/response/AppVersionGetServiceResponse.java
- close #265 
<br/>
- SecurityConfig 쪽은 띄어쓰기가 애매해서 메소드 분리해줬습니다.
> [CHORE] 메소드 띄어쓰기 및 불필요한 import문 제거

- src/main/java/com/soptie/server/routine/controller/v2/docs/DailyRoutineControllerV2Docs.java
- close #306 
<br/>
- 벌레 퇴치
- 확인하시고 승인 후 바로 머지 부탁드립니당
> [FIX] 쿼리 필드명 변경

- src/main/java/com/soptie/server/memberroutine/controller/v1/dto/request/MemberDailyRoutinesCreateRequest.java
- src/main/java/com/soptie/server/memberroutine/controller/v2/MemberDailyRoutineControllerV2.java
- src/main/java/com/soptie/server/memberroutine/controller/v2/docs/MemberDailyRoutineControllerV2Docs.java
- src/main/java/com/soptie/server/memberroutine/service/MemberRoutineCreateService.java
- src/main/java/com/soptie/server/routine/adapter/RoutineFinder.java
- src/main/java/com/soptie/server/routine/repository/RoutineCustomRepository.java
- src/main/java/com/soptie/server/routine/repository/RoutineRepositoryImpl.java
- close #316 
<br/>
- 경로 중복으로 인해 v2로 추가했습니다.
> [FEAT] 데일리 루틴 다중 추가 api

- src/main/java/com/soptie/server/memberroutine/controller/v2/MemberDailyRoutineControllerV2.java
- src/main/java/com/soptie/server/memberroutine/controller/v2/docs/MemberDailyRoutineControllerV2Docs.java
- src/main/java/com/soptie/server/memberroutine/controller/v2/dto/response/MemberDailyRoutinesCreateResponse.java
- src/main/java/com/soptie/server/memberroutine/service/MemberRoutineCreateService.java
- src/main/java/com/soptie/server/memberroutine/service/dto/response/MemberDailyRoutinesCreateServiceResponse.java
- #316 
<br/>
- 클라 쪽에서 200이라면 data가 null이 아니어야 해서 data를 추가하였습니다.
- 개발 도중 루틴 중복 추가 버그를 발견하여 해결하였습니다.
> [REFACTOR] 데일리 루틴 다중 추가 api 수정

- src/main/java/com/soptie/server/domain/conversation/Conversation.java
- src/main/java/com/soptie/server/domain/member/MemberService.java
- src/main/java/com/soptie/server/persistence/adapter/ConversationAdapter.java
- src/test/java/com/soptie/server/domain/member/MemberServiceTest.java
- close #none
<br/>
- 해당 리팩토링 과정 중 중간 PR은 리뷰 X
> [REFACTOR] conversation api

- .github/workflows/deploy.yml
- close #322 
<br/>
- 트리거 변경
- push될 때마다 CD 되는 사항에서 릴리즈 액션 시 CD 되는 트리거로 변경합니다.
> [FIX] CD 트리거 변경

- src/main/java/com/soptie/server/api/controller/dto/response/memberroutine/GetMemberRoutinesResponse.java
- close #305 
<br/>
- 루틴을 id 기준으로 오름차순 정렬합니다.
> [FIX] 진행 중인 루틴 정렬 추가

- src/main/java/com/soptie/server/common/support/ValueConfig.java
> deploy: SP2 실서버 배포

- src/main/java/com/soptie/server/api/controller/MemberMissionApi.java
- src/main/java/com/soptie/server/api/controller/MemberRoutineApi.java
- src/main/java/com/soptie/server/api/controller/docs/MemberMissionApiDocs.java
- src/main/java/com/soptie/server/api/controller/docs/MemberRoutineApiDocs.java
- src/main/java/com/soptie/server/domain/membermission/MemberMissionService.java
- src/main/java/com/soptie/server/domain/memberroutine/MemberRoutineService.java
- src/main/java/com/soptie/server/persistence/adapter/mission/MissionHistoryAdapter.java
- src/main/java/com/soptie/server/persistence/adapter/routine/RoutineHistoryAdapter.java
- close #352 
<br/>
- 달성 기록을 삭제하는 API를 구현했습니다.
#351 PR 머지 후 리뷰를 진행해주세요. (351과 중복되는 내용 포함됨)
> [FEAT] 루틴/미션 달성 기록 삭제 API

- src/main/java/com/soptie/server/domain/membermission/MemberMissionService.java
> [FIX] 미션 달성 기록 저장

- src/main/java/com/soptie/server/api/controller/MemberChallengeApi.java
- src/main/java/com/soptie/server/api/controller/docs/MemberChallengeApiDocs.java
- src/main/java/com/soptie/server/api/controller/dto/request/memberchallenge/CreateMemberChallengeRequest.java
- src/main/java/com/soptie/server/api/controller/dto/response/calendar/DateHistoryResponse.java
- src/main/java/com/soptie/server/api/controller/dto/response/memberchallenge/CreateMemberChallengeResponse.java
- src/main/java/com/soptie/server/api/controller/dto/response/memberchallenge/MemberChallengeResponse.java
- src/main/java/com/soptie/server/domain/challenge/ChallengeHistory.java
- src/main/java/com/soptie/server/domain/challenge/MemberChallengeService.java
- src/main/java/com/soptie/server/domain/memo/MemoService.java
- src/main/java/com/soptie/server/persistence/adapter/challenge/ChallengeAdapter.java
- src/main/java/com/soptie/server/persistence/adapter/challenge/MemberChallengeAdapter.java
- src/main/java/com/soptie/server/persistence/entity/challenge/ChallengeHistoryEntity.java
- src/main/java/com/soptie/server/persistence/repository/challenge/ChallengeHistoryRepository.java
- close #368 
<br/>
- 남아있는 mission 전부 challenge로 수정하였습니다.
> [FIX] 메모 생성

- .github/workflows/deploy.yml
- Dockerfile-dev
- close #374 
<br/>
- 될 때까지 테스트해보겠습니다 ㅎㅎ
> [DEPLOY] 개발 서버 CI/CD

- .github/workflows/deploy.yml
- close #374 
<br/>
- 2차 시도입니다~
> [FIX] add jobs name

- .github/workflows/deploy.yml
- close #374 
<br/>
- 3차 시도입니당
> [FIX] 개발 서버 CI/CD

- .github/workflows/deploy-prod.yml
- Dockerfile-prod
> [DEPLOY] 실서버 CI/CD

- src/main/java/com/soptie/server/domain/challenge/MemberChallengeService.java
- src/main/java/com/soptie/server/domain/challenge/util/ChallengeValidator.java
- src/main/java/com/soptie/server/persistence/adapter/challenge/ChallengeHistoryAdapter.java
- src/main/java/com/soptie/server/persistence/repository/challenge/ChallengeHistoryRepository.java
- close #387 
<br/>
- 오늘 이미 달성한 챌린지 추가 시, 에러 발생
> [FIX] 도전 루틴 무한 추가 버그 수정

- src/main/java/com/soptie/server/api/controller/customroutine/CustomRoutineApi.java
- src/main/java/com/soptie/server/api/controller/customroutine/docs/CustomRoutineApiDocs.java
- src/main/java/com/soptie/server/api/controller/customroutine/dto/CustomRoutineRequest.java
- src/main/java/com/soptie/server/api/controller/customroutine/dto/CustomRoutineRequestDto.java
- src/main/java/com/soptie/server/api/controller/customroutine/dto/CustomRoutineResponse.java
- src/main/java/com/soptie/server/api/controller/customroutine/dto/CustomRoutineResponseDto.java
- src/main/java/com/soptie/server/api/controller/dto/response/SuccessResponse.java
- src/main/java/com/soptie/server/api/controller/memberroutine/MemberRoutineApi.java
- src/main/java/com/soptie/server/api/controller/memberroutine/MemberRoutineApiV2.java
- src/main/java/com/soptie/server/api/controller/memberroutine/docs/MemberRoutineApiDocs.java
- src/main/java/com/soptie/server/api/controller/memberroutine/docs/MemberRoutineApiV2Docs.java
- src/main/java/com/soptie/server/api/controller/memberroutine/dto/AchieveMemberRoutineResponse.java
- src/main/java/com/soptie/server/api/controller/memberroutine/dto/CreateMemberRoutinesRequest.java
- src/main/java/com/soptie/server/api/controller/memberroutine/dto/CreateMemberRoutinesResponse.java
- src/main/java/com/soptie/server/api/controller/memberroutine/dto/GetMemberRoutinesResponse.java
- src/main/java/com/soptie/server/api/controller/memberroutine/dto/MemberRoutineResponse.java
- src/main/java/com/soptie/server/common/utils/MessageUtils.java
- src/main/java/com/soptie/server/config/support/GlobalData.java
- src/main/java/com/soptie/server/domain/customroutine/CustomRoutineCommandService.java
- src/main/java/com/soptie/server/domain/memberroutine/MemberRoutine.java
- src/main/java/com/soptie/server/domain/memberroutine/MemberRoutineReadService.java
- src/main/java/com/soptie/server/domain/memberroutine/MemberRoutineService.java
- src/main/java/com/soptie/server/persistence/adapter/routine/MemberRoutineAdapter.java
- src/main/java/com/soptie/server/persistence/entity/routine/MemberRoutineEntity.java
- src/main/java/com/soptie/server/persistence/global/RoutineStore.java
- src/main/java/com/soptie/server/persistence/global/ThemeStore.java
- src/main/java/com/soptie/server/persistence/repository/routine/MemberRoutineRepository.java
- src/main/java/com/soptie/server/persistence/repository/utils/QueryUtils.java
- close #389 
<br/>
- 커스텀 루틴 관련 CUD API 추가
- 회원 루틴 조회 API 수정 (custom routine 추가, routineId가 null일 경우 커스텀 루틴)
- 일부 package 위치 이동
> [FEATURE] 커스텀 루틴 API

- src/main/java/com/soptie/server/domain/member/Member.java
- src/main/java/com/soptie/server/domain/member/MemberService.java
- src/main/java/com/soptie/server/persistence/converter/MemberConverter.java
- src/main/java/com/soptie/server/persistence/entity/MemberEntity.java
- close #이슈번호
<br/>
- Time 까지 가지고 있을 필요가 없어서 LocalDateTime -> LocalDate 변경
> [FIX] Update Member's column

- .github/workflows/deploy.yml
- close #이슈번호
<br/>
- fcm.json 생성 로직 deploy.yml 누락 추가
> [HOTFIX] fcm.json 생성 로직 추가

- src/main/java/com/soptie/server/common/helper/webhook/model/WebhookLoggerRequest.java
- close #이슈번호
<br/>
- 바보 이슈로 PR 하나 더 😭
> [FIX] 디스코드 연동 코드 수정

- src/main/java/com/soptie/server/api/controller/memberroutine/MemberRoutineApiV2.java
- src/main/java/com/soptie/server/api/controller/memberroutine/docs/MemberRoutineApiV2Docs.java
- src/main/java/com/soptie/server/api/controller/memberroutine/dto/UpdateMemberRoutineRequest.java
- src/main/java/com/soptie/server/config/SecurityConfig.java
- src/main/java/com/soptie/server/domain/customroutine/CustomRoutineCommandService.java
- src/main/java/com/soptie/server/domain/memberroutine/MemberRoutineService.java
- src/main/java/com/soptie/server/domain/memberroutine/RoutineAlarm.java
- src/main/java/com/soptie/server/persistence/adapter/routine/RoutineAlarmAdapter.java
- src/main/java/com/soptie/server/persistence/converter/MemberConverter.java
- src/main/java/com/soptie/server/persistence/entity/routine/MemberRoutineEntity.java
- src/main/java/com/soptie/server/persistence/entity/routine/RoutineAlarmEntity.java
- src/main/java/com/soptie/server/persistence/repository/routine/RoutineAlarmRepository.java
> [HOTFIX] 회원 fcm 토큰 null 에러 수정 및 루틴 알람 생성

- src/main/java/com/soptie/server/domain/customroutine/CustomRoutineCommandService.java
- close #이슈번호
<br/>
- 디스코드에 자세히 언급해놨습니다.
> [HOTFIX] 루틴 알람 관련 버그 수정

- src/main/java/com/soptie/server/domain/member/MemberService.java
> [HOTFIX] fcm 토큰 트랜잭션 적용

- .github/workflows/deploy-prod.yml
> hotfix: add fcm.json logic
