src/main/java/com/soptie/server/member/entity/Member.java, src/main/java/com/soptie/server/memberRoutine/entity/MemberDailyRoutine.java, src/main/java/com/soptie/server/memberRoutine/entity/MemberHappinessRoutine.java, src/main/java/com/soptie/server/routine/entity/daily/DailyRoutine.java, src/main/java/com/soptie/server/routine/entity/daily/DailyTheme.java, src/main/java/com/soptie/server/routine/entity/happiness/HappinessRoutine.java, src/main/java/com/soptie/server/routine/entity/happiness/HappinessSubRoutine.java, src/main/java/com/soptie/server/routine/entity/happiness/HappinessTheme.java
closed #2 
- Routine 편의 메소드 생성 중 필요하여 Member 엔티티 내 메소드 추가했습니다.
- DailyTheme를 ENUM에서 Entity 형식으로 변경함에 따라 Member.themes 칼럼을 일부 임시 수정했습니다.
- DailyTheme에서 이름, 내용, 이미지 url을 가지고 있어 Entity 타입으로 변환했습니다.
- 더미데이터를 제외한 Entity 내 생성자와 편의 메소드를 추가했습니다.
- 전체 Entity의 칼럼에 속성을 추가했습니다.
- HappinessTheme(행복루틴 테마)에 기획 문서를 참고하여 임의로 값을 추가해두었습니다.
=> [ADD] Routine 엔티티 구체화

build.gradle, src/main/java/com/soptie/server/common/config/JpaQueryFactoryConfig.java, src/main/java/com/soptie/server/common/dto/Response.java, src/main/java/com/soptie/server/routine/controller/DailyRoutineController.java, src/main/java/com/soptie/server/routine/dto/DailyThemesResponse.java, src/main/java/com/soptie/server/routine/entity/daily/DailyRoutine.java, src/main/java/com/soptie/server/routine/entity/daily/DailyTheme.java, src/main/java/com/soptie/server/routine/entity/daily/RoutineImage.java, src/main/java/com/soptie/server/routine/message/ResponseMessage.java, src/main/java/com/soptie/server/routine/repository/daily/theme/DailyThemeCustomRepository.java, src/main/java/com/soptie/server/routine/repository/daily/theme/DailyThemeRepository.java, src/main/java/com/soptie/server/routine/repository/daily/theme/DailyThemeRepositoryImpl.java, src/main/java/com/soptie/server/routine/service/DailyRoutineService.java
- close #15 
<br/>
- 예시 API가 필요하다고 하여, 우선 테스트 진행 전 PR 업로드 했습니다.
- DB 세팅 후 추가적인 테스트, 코드 리팩토링, 의논 반영 등 작업 진행하겠습니다.
- 유연한 쿼리 환경을 위해 QueryDSL을 추가했습니다.
- 데일리 루틴의 테마에 따라 이미지 정보가 결정되어 테마 엔티티로 이미지 정보를 이동했습니다.
- 아이콘이 루틴 달성 여부에 관계없이 유색 이미지로 통일되는 것으로 전달받아 무색 이미지는 삭제했습니다.
- 공통 ResponseDTO 클래스를 추가했습니다. 패키지 이름을 통해 클래스 역할이 정의된다고 생각하여 클래스명은 Response로 우선 정의했습니다.
- 자유롭게 의견이나 궁금한 점 있으시면 리뷰로 부탁드려요 :)
=> [FEAT] 데일리 루틴 테마 리스트 조회

src/main/java/com/soptie/server/routine/controller/DailyRoutineController.java, src/main/java/com/soptie/server/routine/dto/DailyRoutinesResponse.java, src/main/java/com/soptie/server/routine/entity/daily/DailyRoutine.java, src/main/java/com/soptie/server/routine/entity/daily/DailyTheme.java, src/main/java/com/soptie/server/routine/entity/daily/RoutineImage.java, src/main/java/com/soptie/server/routine/message/ResponseMessage.java, src/main/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineCustomRepository.java, src/main/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineRepository.java, src/main/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineRepositoryImpl.java, src/main/java/com/soptie/server/routine/service/DailyRoutineService.java, src/main/java/com/soptie/server/routine/service/DailyRoutineServiceImpl.java, src/main/resources/static/docs/open-api-3.0.1.json, src/test/java/com/soptie/server/routine/controller/DailyRoutineControllerTest.java, src/test/java/com/soptie/server/routine/fixture/DailyRoutineFixture.java
- close #20 
<br/>
- Service Layer를 인터페이스로 분리함으로써 Controller과의 결합도와 의존성을 낮췄습니다.
- 이전 PR에서 누락된 테스트 코드를 추가했습니다.
=> [FEAT] 테마 리스트 별 루틴 리스트 조회

src/main/java/com/soptie/server/common/handler/ErrorHandler.java, src/main/java/com/soptie/server/routine/controller/DailyRoutineController.java, src/main/java/com/soptie/server/routine/message/ErrorMessage.java, src/main/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineRepository.java, src/main/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineRepositoryImpl.java, src/main/java/com/soptie/server/routine/service/DailyRoutineService.java, src/main/java/com/soptie/server/routine/service/DailyRoutineServiceImpl.java, src/main/resources/static/docs/open-api-3.0.1.json, src/test/java/com/soptie/server/routine/controller/DailyRoutineControllerTest.java
- close #22 
<br/>
- 이전 PR(테마 리스트 별 데일리 루틴 리스트 조회)이 포함되어 있어요. 이전 PR 병합 후 리뷰 부탁드려요 :)
=> [FEAT] 테마 별 데일리 루틴 리스트 조회

build.gradle, src/main/java/com/soptie/server/auth/controller/AuthController.java, src/main/java/com/soptie/server/auth/dto/SignInRequest.java, src/main/java/com/soptie/server/auth/dto/SignInResponse.java, src/main/java/com/soptie/server/auth/jwt/CustomJwtAuthenticationEntryPoint.java, src/main/java/com/soptie/server/auth/jwt/JwtAuthenticationFilter.java, src/main/java/com/soptie/server/auth/jwt/JwtTokenProvider.java, src/main/java/com/soptie/server/auth/jwt/JwtValidationType.java, src/main/java/com/soptie/server/auth/jwt/UserAuthentication.java, src/main/java/com/soptie/server/auth/message/ErrorMessage.java, src/main/java/com/soptie/server/auth/message/ResponseMessage.java, src/main/java/com/soptie/server/auth/service/AuthService.java, src/main/java/com/soptie/server/auth/service/AuthServiceImpl.java, src/main/java/com/soptie/server/auth/service/KakaoService.java, src/main/java/com/soptie/server/auth/service/KakaoServiceImpl.java, src/main/java/com/soptie/server/auth/vo/Token.java, src/main/java/com/soptie/server/common/config/RestTemplateConfig.java, src/main/java/com/soptie/server/common/config/SecurityConfig.java, src/main/java/com/soptie/server/common/config/ValueConfig.java, src/main/java/com/soptie/server/member/entity/Cotton.java, src/main/java/com/soptie/server/member/entity/Member.java, src/main/java/com/soptie/server/member/message/ErrorMessage.java, src/main/java/com/soptie/server/member/repository/MemberRepository.java, src/main/resources/application-dev.yml
- close #4 
<br/>
- 소설로그인 성공했습니다~
=> [INIT] 시큐리티 및 jwt 기초 세팅

src/main/java/com/soptie/server/memberRoutine/entity/daily/MemberDailyRoutine.java, src/main/java/com/soptie/server/memberRoutine/repository/MemberDailyRoutineCustomRepository.java, src/main/java/com/soptie/server/memberRoutine/repository/MemberDailyRoutineRepositoryImpl.java, src/main/java/com/soptie/server/memberRoutine/scheduler/MemberDailyRoutineScheduler.java, src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineService.java, src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java, src/main/resources/application-dev.yml
- close #70 
<br/>
매일 자정 달성한 루틴의 isAchieve 값이 false로 초기화됩니다.
none
=> [FEAT] 루틴 달성 초기화 스케줄러

src/main/java/com/soptie/server/memberRoutine/repository/MemberDailyRoutineRepositoryImpl.java, src/main/java/com/soptie/server/routine/controller/DailyRoutineController.java, src/main/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineCustomRepository.java, src/main/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineRepository.java, src/main/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineRepositoryImpl.java, src/main/java/com/soptie/server/routine/repository/daily/theme/DailyThemeRepositoryImpl.java, src/main/java/com/soptie/server/routine/service/DailyRoutineServiceImpl.java, src/main/resources/static/docs/open-api-3.0.1.json, src/test/java/com/soptie/server/routine/controller/DailyRoutineControllerTest.java
- close #71 
<br/>
- URI의 직관적인 표현을 위해 "테마 별 데일리 루틴 리스트 조회"에서 경로를 일부 수정했습니다. (theme 추가)
- KR 기준으로 텍스트를 정렬하기 위해 Expressions 변수를 추가했습니다.
- KR 기준 정렬의 쿼리를 표현하기 위해 JPA 제공 메소드에서 QueryDSL 내 쿼리 작성으로 수정했습니다. (테마 별 루틴 조회)
=> [FIX] 정렬 기준 KR로 변경

src/main/java/com/soptie/server/memberRoutine/dto/MemberDailyRoutineResponse.java, src/main/java/com/soptie/server/memberRoutine/entity/daily/CompletedMemberDailyRoutine.java, src/main/java/com/soptie/server/memberRoutine/entity/daily/MemberDailyRoutine.java, src/main/java/com/soptie/server/memberRoutine/repository/CompletedMemberDailyRoutineRepository.java, src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java, src/main/resources/static/docs/open-api-3.0.1.json
- close #74 
<br/>
리팩토링.. 머리 감싸면서 쥐어짜냈는데 더 좋은 코드가 떠오르지 않네용.. 🥺
좀 더 좋은 리팩토링 방식이 있다면.. 훈수 제안 언제나 환영입니다 ㅎㅁㅎ
=> [ADD] 루틴 추가 중 예전 루틴 체크 로직 추가

src/main/java/com/soptie/server/memberRoutine/controller/MemberHappinessRoutineController.java, src/main/java/com/soptie/server/memberRoutine/dto/MemberHappinessRoutineRequest.java, src/main/java/com/soptie/server/memberRoutine/dto/MemberHappinessRoutineResponse.java, src/main/java/com/soptie/server/memberRoutine/entity/happiness/MemberHappinessRoutine.java, src/main/java/com/soptie/server/memberRoutine/repository/MemberHappinessRoutineCustomRepository.java, src/main/java/com/soptie/server/memberRoutine/repository/MemberHappinessRoutineRepository.java, src/main/java/com/soptie/server/memberRoutine/repository/MemberHappinessRoutineRepositoryImpl.java, src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineService.java, src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImpl.java, src/main/java/com/soptie/server/routine/controller/HappinessRoutineController.java, src/main/java/com/soptie/server/routine/repository/happiness/routine/HappinessSubRoutineRepository.java
- close #81 
<br/>
회원 별 행복루틴 조회를 구현하기 전에, 병합 충돌을 피하기 위해서 임의로 해당 브랜치를 병합했습니다.
병합 중 이미 존재하는 에러가 있어 원활한 진행을 위해 임의로 수정해두었습니다,,
보고 괜찮으면 바로 승인하고 머지해주세요!
=> [FIX] 병합 충돌 대응

src/main/java/com/soptie/server/memberRoutine/controller/MemberHappinessRoutineController.java, src/main/java/com/soptie/server/memberRoutine/dto/MemberHappinessRoutinesResponse.java, src/main/java/com/soptie/server/memberRoutine/message/ResponseMessage.java, src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineService.java, src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImpl.java, src/main/java/com/soptie/server/routine/entity/happiness/HappinessSubRoutine.java, src/main/resources/static/docs/open-api-3.0.1.json, src/test/java/com/soptie/server/memberRoutine/controller/MemberHappinessRoutineControllerTest.java, src/test/java/com/soptie/server/memberRoutine/fixture/MemberHappinessRoutineFixture.java
- close #80 
<br/>
- 행복 루틴 추가 PR 병합 후 리뷰 받고 병합 진행하도록 하겠습니다. (충돌 예방 목적)
=> [FEAT] 회원 행복 루틴 조회

src/main/java/com/soptie/server/auth/controller/AuthController.java, src/main/java/com/soptie/server/auth/message/ResponseMessage.java, src/main/java/com/soptie/server/auth/service/AuthService.java, src/main/java/com/soptie/server/auth/service/AuthServiceImpl.java, src/main/java/com/soptie/server/member/controller/MemberController.java, src/main/java/com/soptie/server/member/entity/Member.java, src/main/resources/static/docs/open-api-3.0.1.json, src/test/java/com/soptie/server/auth/controller/AuthControllerTest.java
- close #91 
- 로그아웃 api
- 로그아웃 api test
딱히 없습니다.
=> [FEAT] 로그아웃 api

src/main/java/com/soptie/server/routine/controller/HappinessRoutineController.java, src/main/java/com/soptie/server/routine/repository/happiness/routine/HappinessRoutineCustomRepository.java, src/main/java/com/soptie/server/routine/repository/happiness/routine/HappinessRoutineRepositoryImpl.java, src/main/java/com/soptie/server/routine/service/HappinessRoutineServiceImpl.java, src/main/resources/static/docs/open-api-3.0.1.json
- close #101 
<br/>
- 행복 루틴의 전체 조회를 허용하기 위해 themeId 값을 파라미터 값에서 쿼리 값으로 변경했습니다.
=> [FIX] 테마 별 행복루틴 조회에서 테마 id 값을 쿼리 값으로 변경

src/main/java/com/soptie/server/routine/dto/HappinessRoutinesResponse.java, src/main/java/com/soptie/server/routine/dto/HappinessThemesResponse.java, src/main/java/com/soptie/server/routine/entity/happiness/HappinessSubRoutine.java, src/main/java/com/soptie/server/routine/entity/happiness/RoutineImage.java, src/main/resources/static/docs/open-api-3.0.1.json, src/test/java/com/soptie/server/routine/controller/HappinessRoutineControllerTest.java, src/test/java/com/soptie/server/routine/fixture/HappinessRoutineFixture.java
#79 
<br/>
일단 testcode 두 개 짠거만 먼저 머지하려고요 그럼이제 제게 남은 건 행복루틴 예외처리 테스트 코드 3개군요.. 후후 여러분들 감사합니다.
=> [TEST] 내가 만든 기능들 테스트 코드 작성하기 

src/main/java/com/soptie/server/memberRoutine/repository/MemberDailyRoutineRepository.java, src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java, src/main/java/com/soptie/server/routine/message/ErrorMessage.java, src/main/resources/static/docs/open-api-3.0.1.json
- close #95 
<br/>
- 데일리 루틴 최대 3개 추가 가능, 중복된 루틴 추가 불가능 관련하여 예외 추가했습니다.
- 메소드명은 지피티에게 자문을 구했습니다.. 더 직관적인 메소드명이 떠오른다면 추천해주십쇼!
- 이 외에 더 좋은 코드 리팩토링이 떠오른다면 피드백 리뷰 언제나 환영입니다 :)
=> [ADD] 데일리 루틴 추가 예외처리 추가

src/main/java/com/soptie/server/auth/controller/AuthController.java, src/main/java/com/soptie/server/auth/message/ResponseMessage.java, src/main/java/com/soptie/server/auth/service/AuthService.java, src/main/java/com/soptie/server/auth/service/AuthServiceImpl.java, src/main/java/com/soptie/server/memberDoll/repository/MemberDollRepository.java, src/main/java/com/soptie/server/memberDoll/service/MemberDollService.java, src/main/java/com/soptie/server/memberDoll/service/MemberDollServiceImpl.java, src/main/java/com/soptie/server/memberRoutine/repository/CompletedMemberDailyRoutineRepository.java, src/main/java/com/soptie/server/memberRoutine/service/CompletedMemberDailyRoutineService.java, src/main/java/com/soptie/server/memberRoutine/service/CompletedMemberDailyRoutineServiceImpl.java, src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineService.java, src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java, src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineService.java, src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImpl.java, src/main/java/com/soptie/server/routine/repository/daily/routine/DailyRoutineRepository.java, src/main/resources/static/docs/open-api-3.0.1.json, src/test/java/com/soptie/server/auth/controller/AuthControllerTest.java
- close #92 
<br/>
- 삭제 확인 (소현아 고마워ㅠㅠ)
- 스웨거 업로드 확인
메서드 분리할게 되게 많고 authServiceImpl에서 다른 service를 많이 불러왔어야했는데 한 번 더 좋은 방법이 있는지 생각해주시면 감사하겠습니다.
또한 멤버가 인형, 데일리 루틴, 행복 루틴을 가지고 있을 때에도 삭제해주는 코드를 작성하긴 했으나 테스트를 해보지는 않아서 이후에 계정 인증 문제가 해결되거나 소현이가 숙소에 복귀하면 테스트하고 문제가 있다면 이슈 생성 후 수정하겠습니다.
=> [DELETE] 회원 탈퇴

src/main/java/com/soptie/server/memberRoutine/controller/MemberHappinessRoutineController.java, src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineService.java, src/main/java/com/soptie/server/memberRoutine/service/MemberHappinessRoutineServiceImpl.java
- close #129 
<br/>
- 행복 루틴 조회에서 데이터가 없을 경우를 고려하지 않아, 분기 처리를 추가했습니다.
=> [ADD] 회원 행복루틴 조회, 204 분기 처리 추가

src/main/java/com/soptie/server/auth/service/KakaoServiceImpl.java
- close #126 
<br/>
- 외부 API에서 발생하는 예외를 처리합니다.
none
=> [ADD] 외부 API 예외 처리

src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineService.java, src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java, src/main/java/com/soptie/server/routine/controller/DailyRoutineController.java, src/main/java/com/soptie/server/routine/service/DailyRoutineService.java, src/main/java/com/soptie/server/routine/service/DailyRoutineServiceImpl.java, src/test/java/com/soptie/server/routine/controller/DailyRoutineControllerTest.java, src/test/java/com/soptie/server/routine/service/DailyRoutineServiceTest.java
- close #154 
<br/>
- 회원이 추가한 데일리 루틴은 조회할 수 없도록 일부 수정했습니다.
=> [FIX] 테마별 데일리 루틴 조회 수정

src/main/java/com/soptie/server/memberRoutine/entity/daily/CompletedMemberDailyRoutine.java, src/main/java/com/soptie/server/memberRoutine/entity/daily/MemberDailyRoutine.java, src/main/java/com/soptie/server/memberRoutine/service/MemberDailyRoutineServiceImpl.java
- close #160 
<br/>
- 솜뭉치 무한 생성을 막기 위해, 오늘 달성하고 삭제한 데일리 루틴은 다시 추가해도 달성 완료된 루틴으로 추가합니다.
=> [FIX] 데일리 솜뭉치 무한 개 생성 막기

src/main/java/com/soptie/server/auth/controller/AuthController.java, src/main/java/com/soptie/server/auth/dto/TokenResponse.java, src/main/java/com/soptie/server/auth/jwt/JwtAuthenticationFilter.java, src/main/java/com/soptie/server/auth/message/ErrorCode.java, src/main/java/com/soptie/server/auth/message/SuccessMessage.java, src/main/java/com/soptie/server/auth/service/AuthService.java, src/main/java/com/soptie/server/auth/service/AuthServiceImpl.java, src/main/java/com/soptie/server/common/util/Constant.java, src/main/java/com/soptie/server/member/repository/MemberRepository.java, src/main/java/com/soptie/server/member/service/MemberService.java, src/main/java/com/soptie/server/member/service/MemberServiceImpl.java, src/main/resources/static/docs/open-api-3.0.1.json, src/test/java/com/soptie/server/auth/controller/AuthControllerTest.java
=> [FEAT] 토큰 재발급 api

src/main/java/com/soptie/server/memberRoutine/repository/MemberDailyRoutineRepositoryImpl.java
- close #164
<br/>
- 달성 완료되지 않은(false) 루틴 먼저
- 달성 횟수 많은 루틴 먼저
- 가나다 순
- 안드로이드 apk 과제 진행 종료 후(1/20 1시 예정) 배포합니다.
=> [ADD] 회원 데일리 루틴 정렬 조건 추가

src/main/java/com/soptie/server/common/config/ValueConfig.java, src/main/java/com/soptie/server/version/dto/AppVersionResponse.java, src/main/java/com/soptie/server/version/service/VersionServiceImpl.java, src/main/resources/static/docs/open-api-3.0.1.json, src/test/java/com/soptie/server/version/controller/VersionControllerTest.java
- close #178 
<br/>
- 기획 요청으로 업데이트 알림 문구를 수정했습니다. ([슬랙 논의 자료](https://w1702988084-f1k570985.slack.com/archives/C06D0RQRNHG/p1706597667893949?thread_ts=1706496474.599839&cid=C06D0RQRNHG))
- 클라 요청으로 업데이트 알림 문구를 title, content로 구분했습니다.
=> [FIX] 업데이트 알림 문구 수정

src/main/java/com/soptie/server/routine/entity/daily/DailyTheme.java, src/test/java/com/soptie/server/routine/repository/daily/theme/DailyThemeRepositoryTest.java, src/test/java/com/soptie/server/routine/service/DailyRoutineServiceImplTest.java, src/test/java/com/soptie/server/support/DailyThemeFixture.java, src/test/java/com/soptie/server/support/RepositoryTest.java
none (공통 이슈 사용)
<br/>
- Repository 테마 조회 기능 테스트
- Service 테마 조회 기능 테스트
=> [TEST] 데일리 루틴 테마 전체 조회 테스트

src/main/java/com/soptie/server/conversation/entity/Conversation.java, src/main/java/com/soptie/server/doll/entity/Doll.java, src/main/java/com/soptie/server/memberDoll/entity/MemberDoll.java, src/test/java/com/soptie/server/doll/service/DollServiceImplTest.java, src/test/java/com/soptie/server/member/service/MemberServiceImplTest.java, src/test/java/com/soptie/server/support/ConversationFixture.java, src/test/java/com/soptie/server/support/DollFixture.java, src/test/java/com/soptie/server/support/MemberDollFixture.java
- close #210 
<br/>
- MemberService 테스트 결과
- deleteMember()는 단순히 jpa repository에서 delete 메소드 호출하는 거라 생략했습니다.
- getMemberHomeInfo()에서 불러올 정보가 많아 코드가 꽤 복잡해진 거 같은데 조금 더 좋은 방안이 떠오르신다면 공유해주시면 감사하겠습니다.
=> [TEST] MemberService 테스트

src/main/java/com/soptie/server/routine/controller/daily/DailyRoutineApi.java
- #117 
<br/>
- 데일리 루틴 관련 API 스웨거 정보(어노테이션) 추가했습니다.
=> [ADD] 데일리 루틴 Swagger 정보 추가

src/main/java/com/soptie/server/expert/entity/Expert.java, src/main/java/com/soptie/server/memberRoutine/entity/MemberRoutine.java, src/main/java/com/soptie/server/routine/entity/Routine.java, src/main/java/com/soptie/server/routine/entity/RoutineType.java, src/main/java/com/soptie/server/routine/entity/challenge/Challenge.java, src/main/java/com/soptie/server/theme/entity/ImageInfo.java, src/main/java/com/soptie/server/theme/entity/Theme.java
- close #225 
<br/>
- [회의록](https://www.notion.so/2cfc12ed13494845b95e0ecca3e3429d?pvs=4)
- 전문가, 테마, 루틴, 도전 루틴 상세, 회원의 루틴 테이블을 2차 스프린트에 맞춰 추가했습니다.
- 삭제된 회원의 루틴 테이블은 변동성이 있을 점을 고려하여, 관련 비즈니스 로직을 구현하면서 추가하는 것이 좋을 것 같아 우선 보류했습니다.
- 추가 의견 있으면 리뷰 부탁드려요 :)
=> [REFACTOR] DB 테이블 재구성

src/main/java/com/soptie/server/routine/service/dto/response/DailyRoutineListGetServiceResponse.java, src/main/java/com/soptie/server/routine/service/dto/response/HappinessSubRoutineListGetServiceResponse.java, src/main/java/com/soptie/server/theme/entity/ThemeImageInfo.java, src/main/java/com/soptie/server/theme/service/dto/response/ThemeListGetServiceResponse.java, src/test/java/com/soptie/server/support/fixture/ThemeFixture.java
=> [HOTFIX] 구버전 이미지 이슈 대응

src/main/java/com/soptie/server/conversation/adapter/ConversationFinder.java, src/main/java/com/soptie/server/doll/adapter/DollFinder.java, src/main/java/com/soptie/server/member/adapter/MemberDeleter.java, src/main/java/com/soptie/server/member/service/MemberServiceImpl.java, src/main/java/com/soptie/server/memberDoll/adapter/MemberDollSaver.java, src/main/java/com/soptie/server/memberRoutine/service/MemberRoutineCreateService.java, src/test/java/com/soptie/server/member/service/MemberServiceImplTest.java
- close #271 
<br/>
- 멤버 프로필 생성 api
- 회원 탈퇴 api
- 코드 리팩토링 후 멤버 프로필 생성 테스트가 잘 돌아가지 않는데 이는 멤버 통합 테스트에서 진행하는 것이 맞다 생각해 일단 주석처리 해놨습니다.
- 일단 MemberRoutineService와 MemberDollService에서 하던 일을 그대로 가져온 거라 따로 검증은 하지 않았는데 너무 위험한 행동일까요...?
=> [REFACTOR] MemberService 순환 참조 문제

src/main/java/com/soptie/server/common/config/SecurityConfig.java, src/main/java/com/soptie/server/routine/adapter/RoutineFinder.java, src/main/java/com/soptie/server/routine/controller/v2/DailyRoutineControllerV2.java, src/main/java/com/soptie/server/routine/controller/v2/docs/DailyRoutineControllerV2Docs.java, src/main/java/com/soptie/server/routine/controller/v2/dto/response/DailyRoutineListAcquireResponseV2.java, src/main/java/com/soptie/server/routine/service/RoutineService.java, src/main/java/com/soptie/server/routine/service/vo/RoutineVO.java, src/test/java/com/soptie/server/routine/service/integration/RoutineServiceIntegrationTest.java
- close #298 
<br/>
- 파라미터 값으로 받은 테마 기준으로 루틴을 조회하는 기능이기 때문에, 테마 정보는 id 외에 생략했습니다.
- 파라미터 값으로 받은 테마 id 목록 값을 순서 그대로 반환하도록 했습니다.
- LinkedHashMap 사용
- stream()이 for문보다 느린 특징과, 사용시 가독성이 크게 향상되지 않는다는 점에서 for문 사용
- 파라미터 값으로 받는 theme id 목록에서 중복을 허용하지 않기 위해 Set 자료구조를 사용했습니다.
=> [FEAT] 테마별 데일리 루틴 목록 조회(public, 온보딩) 기능 구현

src/main/java/com/soptie/server/memberroutine/controller/v2/MemberChallengeRoutineControllerV2.java, src/main/java/com/soptie/server/memberroutine/controller/v2/docs/MemberChallengeRoutineControllerV2Docs.java, src/main/java/com/soptie/server/memberroutine/controller/v2/dto/response/MemberChallengeRoutineAcquireResponseV2.java, src/main/java/com/soptie/server/memberroutine/service/MemberRoutineReadService.java, src/main/java/com/soptie/server/memberroutine/service/dto/request/MemberChallengeAcquireServiceRequest.java, src/main/java/com/soptie/server/memberroutine/service/dto/request/MemberChallengeRoutineAcquireServiceRequest.java, src/main/java/com/soptie/server/memberroutine/service/dto/response/MemberChallengeRoutineAcquireServiceResponse.java, src/test/java/com/soptie/server/memberroutine/service/MemberRoutineServiceTest.java, src/test/java/com/soptie/server/memberroutine/service/integration/MemberRoutineServiceIntegrationTest.java
- close #282 
<br/>
- 회원 도전 루틴 조회 (회원 도전 루틴이 존재하지 않을 때)
- 회원 도전 루틴 조회 (회원 도전 루틴이 존재할 때)
- 회원 루틴 조회 V2 테스트
- 회원 데일리, 도전 루틴 조회를 위한 ServiceRequestDto의 내용이 v1, v2 둘 다 memberId 하나로 동일한 상황인데 모두 통일시키는 거 어떤가요? 통일시킨다면 dto 4개가 1개로 줄어듭니다!
=> [FEAT] 회원 도전 루틴 조회

src/main/java/com/soptie/server/common/config/ValueConfig.java, src/main/java/com/soptie/server/memberroutine/repository/dto/MemberChallengeResponse.java, src/main/java/com/soptie/server/routine/adapter/ChallengeFinder.java, src/main/java/com/soptie/server/routine/controller/v2/ChallengeRoutineControllerV2.java, src/main/java/com/soptie/server/routine/controller/v2/docs/ChallengeRoutineControllerV2Docs.java, src/main/java/com/soptie/server/routine/controller/v2/dto/response/ChallengeRoutineListAcquireResponseV2.java, src/main/java/com/soptie/server/routine/message/RoutineSuccessMessage.java, src/main/java/com/soptie/server/routine/service/RoutineService.java, src/main/java/com/soptie/server/routine/service/dto/response/ChallengeRoutineListAcquireServiceResponse.java, src/main/java/com/soptie/server/routine/service/dto/response/HappinessSubRoutineListGetServiceResponse.java, src/main/java/com/soptie/server/routine/service/vo/ChallengeVO.java, src/main/java/com/soptie/server/theme/adapter/ThemeFinder.java, src/test/java/com/soptie/server/memberroutine/service/integration/MemberRoutineServiceIntegrationTest.java, src/test/java/com/soptie/server/routine/service/integration/RoutineServiceIntegrationTest.java
- close #284 
<br/>
- 도전 루틴 조회 api
- 도전 루틴 조회 테스트
- 계속해서 리뷰해주신 VO 활용, dto를 좀 더 깔끔하게 작성해보고자 노력했습니다!
- 소현님이 이전에 작성해주신 코드 참고해서 더 원활하게 짤 수 있었습니다.
=> [FEAT] 도전 루틴 목록 조회

src/main/java/com/soptie/server/routine/adapter/RoutineFinder.java, src/main/java/com/soptie/server/routine/controller/v1/dto/response/HappinessRoutineListAcquireResponse.java, src/main/java/com/soptie/server/routine/controller/v2/dto/response/DailyRoutineListAcquireResponseV2.java, src/main/java/com/soptie/server/routine/controller/v2/dto/response/DailyRoutinesAcquireResponseV2.java, src/main/java/com/soptie/server/routine/service/RoutineService.java, src/test/java/com/soptie/server/routine/service/DailyRoutineServiceTest.java, src/test/java/com/soptie/server/routine/service/integration/RoutineServiceIntegrationTest.java
- #308 
<br/>
- build 성공 대체
- RoutineVO 타입을 Routine으로 변환하는 볼륨이 생각보다 커서 PR 따로 생성합니다.
- [Map 관련 이슈](https://github.com/Team-Sopetit/Sopetit-server/pull/309#discussion_r1685821487)도 함께 포함합니다.
=> [FIX] Daily Routine 조회 기능 구현 (2)

src/main/java/com/soptie/server/memberroutine/adapter/MemberRoutineFinder.java, src/main/java/com/soptie/server/memberroutine/repository/MemberRoutineRepository.java, src/main/java/com/soptie/server/routine/adapter/RoutineFinder.java, src/main/java/com/soptie/server/routine/controller/v1/dto/response/HappinessRoutineListAcquireResponse.java, src/main/java/com/soptie/server/routine/controller/v2/DailyRoutineControllerV2.java, src/main/java/com/soptie/server/routine/controller/v2/docs/DailyRoutineControllerV2Docs.java, src/main/java/com/soptie/server/routine/controller/v2/dto/response/DailyRoutineListAcquireResponseV2.java, src/main/java/com/soptie/server/routine/controller/v2/dto/response/DailyRoutinesAcquireResponseV2.java, src/main/java/com/soptie/server/routine/service/RoutineService.java, src/test/java/com/soptie/server/routine/service/DailyRoutineServiceTest.java, src/test/java/com/soptie/server/routine/service/integration/RoutineServiceIntegrationTest.java
- close #308 
<br/>
- test 대체
- 데일리 루틴 목록 조회 기능을 구현했습니다.
- 논의 중인 컨벤션(ex. DTO/VO 활용 범위)은 임의로 기존 클래스와 통일하여 작업했습니다.
=> [FEAT] Daily Routine 목록 조회(in add view) 기능 구현

src/main/java/com/soptie/server/memberroutine/controller/v1/MemberDailyRoutineController.java, src/main/java/com/soptie/server/memberroutine/controller/v1/MemberHappinessRoutineController.java, src/main/java/com/soptie/server/memberroutine/controller/v1/dto/response/MemberDailyRoutineAchieveResponse.java, src/main/java/com/soptie/server/memberroutine/entity/MemberRoutine.java, src/main/java/com/soptie/server/memberroutine/service/MemberRoutineUpdateService.java, src/main/java/com/soptie/server/memberroutine/service/dto/response/MemberRoutineAchieveServiceResponse.java, src/test/java/com/soptie/server/memberroutine/service/MemberRoutineServiceTest.java
- close #274 
<br/>
- 캐시 누락 사유
- 캐시를 사용하기 위해서는 복구를 위한 원본 데이터가 필요합니다.
- 의논한 로직에서는 원본 데이터(ex. 취소 이력)를 담고 있지 않기 때문에 캐싱 장애 발생 시 데이터를 복구할 길이 없습니다.
- 따라서 캐싱을 진행하지 않고, isAchieveToday 칼럼 하나로 로직 체크가 충분히 가능하다고 판단하여 이처럼 진행했습니다.
=> [ADD] 데일리 루틴 달성 취소 로직 추가

src/main/java/com/soptie/server/api/controller/docs/AuthApiDocs.java, src/main/java/com/soptie/server/api/controller/dto/response/member/GetHomeInfoResponse.java, src/main/java/com/soptie/server/domain/doll/DollType.java, src/main/java/com/soptie/server/temporary/TemporaryApi.java, src/main/java/com/soptie/server/temporary/data/ThemeData.java, src/main/java/com/soptie/server/temporary/dto/CreateMemberDailyRoutine.java, src/main/java/com/soptie/server/temporary/dto/DailyRoutineThemesResponse.java, src/main/java/com/soptie/server/temporary/dto/DailyRoutinesResponse.java, src/main/java/com/soptie/server/temporary/dto/DollResponse.java, src/main/java/com/soptie/server/temporary/dto/GetDailyRoutinesResponse.java, src/main/java/com/soptie/server/temporary/dto/GetHappinessRoutinesResponse.java, src/main/java/com/soptie/server/temporary/dto/GetHappinessSubRoutinesResponse.java, src/main/java/com/soptie/server/temporary/dto/GetMemberDailyRoutinesResponse.java, src/main/java/com/soptie/server/temporary/dto/HappinessRoutineThemesResponse.java, src/main/java/com/soptie/server/temporary/dto/MemberHappinessRoutinesResponse.java
- close #334 
<br/>
- Swagger에서 동작하지 않는 로그인/토큰재발급 api 이슈 대응했습니다.
=> [FIX] API version1 싱크 통일

src/main/java/com/soptie/server/api/web/advice/ErrorHandler.java, src/main/java/com/soptie/server/domain/member/MemberCotton.java, src/main/java/com/soptie/server/domain/member/MemberService.java
- close #339 
<br/>
- `솜뭉치 주기 api`에서 회원의 솜뭉치 개수가 0 이하이면 예외를 반환한다.
=> [ADD] 솜뭉치 개수가 0 이하일 경우 예외 처리 추가

src/main/java/com/soptie/server/api/controller/MemberApi.java, src/main/java/com/soptie/server/api/controller/docs/MemberApiDocs.java, src/main/java/com/soptie/server/api/controller/dto/response/member/MemberProfileResponse.java, src/main/java/com/soptie/server/api/controller/generic/SuccessMessage.java, src/main/java/com/soptie/server/domain/member/Member.java, src/main/java/com/soptie/server/domain/member/MemberService.java, src/main/java/com/soptie/server/persistence/entity/MemberEntity.java
- close #354 
<br/>
- 회원 정보를 조회하는 API 개발
- 확장성을 위해 회원의 정보를 조회하는 API를 추가하고, 이번 스프린트에서 필요한 회원가입일자(createdAt)만 우선 포함했습니다.
- #353 PR 머지 후 리뷰를 진행해주세요. (중복 내용 포함)
=> [FEAT] 회원 정보 조회 API

src/main/java/com/soptie/server/api/controller/MemoApi.java, src/main/java/com/soptie/server/api/controller/dto/request/memo/CreateMemoRequest.java, src/main/java/com/soptie/server/api/controller/dto/request/memo/ModifyMemoRequest.java, src/main/java/com/soptie/server/api/controller/dto/response/memo/CreateMemoResponse.java, src/main/java/com/soptie/server/api/controller/generic/SuccessMessage.java, src/main/java/com/soptie/server/domain/membermission/MemberMissionService.java, src/main/java/com/soptie/server/domain/memberroutine/MemberRoutineService.java, src/main/java/com/soptie/server/domain/memo/Memo.java, src/main/java/com/soptie/server/domain/memo/MemoService.java, src/main/java/com/soptie/server/persistence/adapter/MemoAdapter.java, src/main/java/com/soptie/server/persistence/adapter/mission/MissionHistoryAdapter.java, src/main/java/com/soptie/server/persistence/adapter/routine/RoutineHistoryAdapter.java, src/main/java/com/soptie/server/persistence/entity/MemoEntity.java, src/main/java/com/soptie/server/persistence/entity/mission/MissionHistoryEntity.java, src/main/java/com/soptie/server/persistence/entity/routine/RoutineHistoryEntity.java, src/main/java/com/soptie/server/persistence/repository/MemoRepository.java, src/main/java/com/soptie/server/persistence/repository/mission/MissionHistoryRepository.java, src/main/java/com/soptie/server/persistence/repository/routine/RoutineHistoryRepository.java
- close #356 
<br/>
- 메모 생성
- 메모 수정
- 메모 삭제
- 루틴 미달성 날짜에 메모 작성 시도한다면 예외 발생
- 일단은 memberId만 넣고 해결했습니다.  캘린더 조회 작업 시 필요하다면 컬럼 더 추가하겠습니다.
- 갑자기 커밋, 브랜치 컨벤션 스타일이 바뀌셔서 따라가고자 노력했습니다 ㅋㅋㅋ
=> [FEAT] 메모 관련 기능

src/main/java/com/soptie/server/api/controller/dto/response/calendar/DateHistoryResponse.java, src/main/java/com/soptie/server/common/support/ValueConfig.java, src/main/java/com/soptie/server/domain/memo/MemoService.java, src/main/java/com/soptie/server/persistence/adapter/MemoAdapter.java, src/main/java/com/soptie/server/persistence/entity/MemoEntity.java, src/main/java/com/soptie/server/persistence/repository/MemoRepository.java
- close #362 
<br/>
- 메모 중복 생성 방지 (동일 날짜)
- 캘린더 조회 시, 테마 순서로 정렬 및 도전 -> 데일리 순으로 전달
- 저번에 리뷰 주신 Querydsl을 활용하는 방식도 적용하려 했으나 좀 더 공부하고 해보겠습니다.
=> [FIX] 메모 생성 및 캘린더 조회
